# Generated by Django 5.1.7 on 2025-03-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=78)),
                ('city', models.CharField(max_length=78)),
                ('passbywhome', models.CharField(max_length=78)),
                ('roll', models.IntegerField(max_length=78)),
            ],
        ),
    ]
